"""
Fit and evaluate the baseline forecasters.

This script defines the *pattern* every future model will follow: load the
cached dataset, split by time, fit on train, predict on validation, score.
When we add XGBoost and the PINN later, they slot into this same loop with
zero changes to the evaluation logic.

Test set is deliberately not touched here. Test is the final-reporting set,
opened exactly once after the PINN is fully tuned — anything else is
hyperparameter-hacking against test data and inflates results.

Usage:
    python scripts/run_baselines.py
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

import pandas as pd

from solar_forecast.baselines import (
    DailySeasonalNaive,
    Forecaster,
    HourOfYearClimatology,
    LinearWeather,
    Persistence,
)
from solar_forecast.metrics import Metrics, evaluate, skill_score
from solar_forecast.preprocess import load_dataset
from solar_forecast.splits import Split, split_dataset

ROOT = Path(__file__).resolve().parent.parent
REPORT_DIR = ROOT / "reports"

# Predictable order — persistence first (it's the reference for skill score),
# then increasing sophistication. Keeping the order stable matters because the
# results table reads top-to-bottom and we want the story to make sense.
BASELINES: list[Forecaster] = [
    Persistence(),
    DailySeasonalNaive(),
    HourOfYearClimatology(),
    LinearWeather(),
]


def run_one(
    model: Forecaster,
    train: pd.DataFrame,
    val: pd.DataFrame,
    target_col: str,
) -> tuple[Metrics, Metrics]:
    """Fit on train, evaluate on both train (sanity) and val (the real number)."""
    model.fit(train)
    train_metrics = evaluate(train[target_col], model.predict(train))
    val_metrics = evaluate(val[target_col], model.predict(val))
    return train_metrics, val_metrics


def render_report(rows: list[dict]) -> str:
    """Build a markdown table from per-model result rows."""
    header = (
        "# Baseline Results\n\n"
        "_Generated by `scripts/run_baselines.py`._\n\n"
        "All metrics computed on the validation set (2018). Skill scores are\n"
        "relative to the persistence baseline — positive means better than persistence,\n"
        "negative means worse.\n\n"
        "| Model | Val RMSE | Val MAE | Skill (vs persistence) | n |\n"
        "|---|---:|---:|---:|---:|\n"
    )
    body = "\n".join(
        f"| {r['name']} | {r['val_rmse']:.4f} | {r['val_mae']:.4f} | "
        f"{r['skill']:+.3f} | {r['n']:,} |"
        for r in rows
    )
    return header + body + "\n"


def main() -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )
    log = logging.getLogger(__name__)
    target_col = "DE_solar_cf"

    log.info("Loading preprocessed dataset")
    df = load_dataset()
    log.info("Dataset shape: %s, target column: %s", df.shape, target_col)

    train, val, _test = split_dataset(df, split=Split())
    log.info("Train: %s rows (%s → %s)", f"{len(train):,}", train.index.min(), train.index.max())
    log.info("Val:   %s rows (%s → %s)", f"{len(val):,}", val.index.min(), val.index.max())

    # Compute persistence baseline first so it can serve as the skill-score reference.
    persistence_val: Metrics | None = None
    rows = []

    for model in BASELINES:
        log.info("Running %s", model.name)
        train_m, val_m = run_one(model, train, val, target_col)

        if model.name == "persistence":
            persistence_val = val_m
            skill = 0.0    # by definition, persistence has zero skill vs itself
        else:
            assert persistence_val is not None, "persistence must run first"
            skill = skill_score(val_m, persistence_val, metric="rmse")

        rows.append({
            "name": model.name,
            "val_rmse": val_m.rmse,
            "val_mae": val_m.mae,
            "skill": skill,
            "n": val_m.n_samples,
        })
        log.info("  train: %s", train_m)
        log.info("  val:   %s  skill=%.3f", val_m, skill)

    # Print the headline table to stdout for instant feedback,
    # and also persist it as a markdown report we can commit.
    report = render_report(rows)
    print("\n" + report)

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORT_DIR / "baselines.md"
    report_path.write_text(report, encoding="utf-8")
    log.info("Wrote %s", report_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
