"""
Fit and evaluate every forecaster: simple baselines, linear models, XGBoost.

Pipeline:
    1. Load preprocessed parquet (from scripts/preprocess.py)
    2. Add physics features (solar position, G_POA, cell temp, theoretical CF)
    3. Add temporal features (lag-1h, lag-24h, lag-168h, calendar sin/cos)
    4. Chronological split into train / val / test
    5. For each forecaster: fit on train, predict val, score
    6. Log everything to MLflow + write a markdown summary

Test set is not touched. It opens exactly once at the end of the project.

Usage:
    python scripts/run_baselines.py
    mlflow ui                     # then open http://localhost:5000
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

import pandas as pd

from solar_forecast.baselines import (
    DailySeasonalNaive,
    Forecaster,
    HourOfYearClimatology,
    LinearPhysics,
    LinearWeather,
    Persistence,
    PurePhysics,
    XGBoostForecaster,
)
from solar_forecast.features import add_calendar_features, add_lag_features
from solar_forecast.metrics import Metrics, evaluate, skill_score
from solar_forecast.physics import add_physics_features
from solar_forecast.preprocess import load_dataset
from solar_forecast.splits import Split, split_dataset
from solar_forecast.tracking import configure as configure_mlflow, log_model_run

ROOT = Path(__file__).resolve().parent.parent
REPORT_DIR = ROOT / "reports"
TARGET = "DE_solar_cf"

# Feature sets for the XGBoost variants. Each tells a different story:
# - weather: matches linear_weather; isolates "linearity vs nonlinearity"
# - physics: matches linear_physics; isolates "do physics features help nonlinear models?"
# - lag:     full feature set with lagged targets; the strongest baseline
XGB_FEATURE_SETS: dict[str, tuple[str, ...]] = {
    "xgb_weather": ("DE_ghi", "DE_temperature"),
    "xgb_physics": (
        "DE_ghi", "DE_temperature",
        "DE_g_poa", "DE_cf_theory", "DE_clearness_index",
        "DE_t_cell_c", "DE_solar_elevation_deg",
    ),
    "xgb_lag": (
        "DE_ghi", "DE_temperature",
        "DE_g_poa", "DE_cf_theory", "DE_clearness_index",
        "DE_t_cell_c", "DE_solar_elevation_deg",
        "DE_solar_cf_lag_1h", "DE_solar_cf_lag_24h", "DE_solar_cf_lag_168h",
        "hour_sin", "hour_cos", "doy_sin", "doy_cos",
    ),
}


def run_one(model: Forecaster, train: pd.DataFrame, val: pd.DataFrame) -> tuple[Metrics, Metrics]:
    """Fit, then evaluate on both sets. Returns (train_metrics, val_metrics)."""
    model.fit(train)
    train_metrics = evaluate(train[TARGET], model.predict(train))
    val_metrics = evaluate(val[TARGET], model.predict(val))
    return train_metrics, val_metrics


def render_report(rows: list[dict]) -> str:
    """Markdown table from per-model result rows."""
    header = (
        "# Model Results\n\n"
        "_Generated by `scripts/run_baselines.py`._ "
        "Open `mlflow ui` for the interactive comparison view.\n\n"
        "All metrics on the 2018 validation set. Skill scores vs persistence "
        "(positive = better, negative = worse).\n\n"
        "| Model | Val RMSE | Val MAE | Skill | n |\n"
        "|---|---:|---:|---:|---:|\n"
    )
    body = "\n".join(
        f"| {r['name']} | {r['val_rmse']:.4f} | {r['val_mae']:.4f} | "
        f"{r['skill']:+.3f} | {r['n']:,} |"
        for r in rows
    )
    return header + body + "\n"


def make_xgb(name: str, features: tuple[str, ...]) -> XGBoostForecaster:
    """Construct an XGBoost forecaster and set its display name."""
    m = XGBoostForecaster(target_col=TARGET, feature_cols=features)
    m.name = name
    return m


def main() -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
        datefmt="%H:%M:%S",
    )
    log = logging.getLogger(__name__)

    log.info("Loading preprocessed dataset")
    df = load_dataset()
    log.info("Adding physics features")
    df = add_physics_features(df, country="DE")
    log.info("Adding lag and calendar features")
    df = add_lag_features(df, target_col=TARGET)
    df = add_calendar_features(df)
    log.info("Final shape: %s", df.shape)

    train, val, _test = split_dataset(df, split=Split())
    log.info("Train: %s rows / Val: %s rows", f"{len(train):,}", f"{len(val):,}")

    configure_mlflow("solar-forecast-baselines")

    models: list[Forecaster] = [
        Persistence(),
        DailySeasonalNaive(),
        HourOfYearClimatology(),
        LinearWeather(),
        PurePhysics(),
        LinearPhysics(),
        make_xgb("xgb_weather", XGB_FEATURE_SETS["xgb_weather"]),
        make_xgb("xgb_physics", XGB_FEATURE_SETS["xgb_physics"]),
        make_xgb("xgb_lag", XGB_FEATURE_SETS["xgb_lag"]),
    ]

    persistence_val: Metrics | None = None
    rows = []

    for model in models:
        log.info("Running %s", model.name)
        train_m, val_m = run_one(model, train, val)

        if model.name == "persistence":
            persistence_val = val_m
            skill = 0.0
        else:
            assert persistence_val is not None
            skill = skill_score(val_m, persistence_val, metric="rmse")

        rows.append({
            "name": model.name,
            "val_rmse": val_m.rmse,
            "val_mae": val_m.mae,
            "skill": skill,
            "n": val_m.n_samples,
        })

        # Log to MLflow
        params: dict[str, object] = {"model_class": type(model).__name__}
        if isinstance(model, XGBoostForecaster):
            params["n_estimators"] = model.n_estimators
            params["learning_rate"] = model.learning_rate
            params["max_depth"] = model.max_depth
        feature_cols = (
            getattr(model, "_fitted_features", None)
            or getattr(model, "feature_cols", None)
        )
        feature_importance = (
            model.feature_importance
            if isinstance(model, XGBoostForecaster)
            else None
        )
        log_model_run(
            model_name=model.name,
            params=params,
            metrics={
                "train_rmse": train_m.rmse,
                "train_mae": train_m.mae,
                "val_rmse": val_m.rmse,
                "val_mae": val_m.mae,
                "skill_vs_persistence": skill,
                "n_val": float(val_m.n_samples),
            },
            feature_cols=list(feature_cols) if feature_cols else None,
            feature_importance=feature_importance,
        )
        log.info("  val: %s  skill=%+.3f", val_m, skill)

    report = render_report(rows)
    print("\n" + report)

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORT_DIR / "baselines.md"
    report_path.write_text(report, encoding="utf-8")
    log.info("Wrote %s", report_path)
    log.info("Run `mlflow ui` and open http://localhost:5000 for the comparison view")
    return 0


if __name__ == "__main__":
    sys.exit(main())
